name: aim_adm
channels:
    - conda-forge
    - pytorch
dependencies:
  - black
  - dask
  - ipycytoscape
  - ipykernel
  - matplotlib
  - mimesis
  - numpy
  - pandas
  - seaborn
  - pytorch:pytorch
  - scikit-learn